compilerOptions:
  declaration: true
  esModuleInterop: true
  experimentalDecorators: true
  module: ESNext
  moduleResolution: Node
  noImplicitAny: true
  strictNullChecks: true
  strictPropertyInitialization: true
  target: ESNext
  useDefineForClassFields: true
