compilerOptions:
  declaration: true
  esModuleInterop: true
  experimentalDecorators: true
  module: ESNext
  moduleResolution: Node
  noImplicitAny: true
  strict: true
  target: ESNext
  useDefineForClassFields: true
