compilerOptions:
  declaration: true
  esModuleInterop: true
  experimentalDecorators: true
  module: ESNext
  moduleResolution: Node
  noImplicitAny: true
  outDir: ../../../out # Path resolution hack cause outDir's relativity
  strict: true
  target: ESNext
  useDefineForClassFields: true
